### PR TITLE
Signup Error Handling + Error Handling Tests

### PR DESCRIPTION
**Pull request by IbrahimBilal2005**
Added the following error handing for user signup:
- First name can only contain alphabetical characters
- last name can only contains alphabetical characters
- A gender must be selected (cannot be empty)
- Must be at least 18 years old
- An interest must be selected (cannot be empty)
-  EDIT: password must be at least 8 characters long

Added the following error handling for event poster signup:
- SOP link must be a valid link (begins with https://)
- Organization name cannot be empty

All related tests are passing

QUESTIONS: 
- Should I add a password strength requirement? (contains numbers, symbols, capitals etc.) 
- Are there any other requirements / restrictions in the signup process that I should add?

### CODE REVIEW

**Review by W-Akrabi — CHANGES_REQUESTED** [review]
These are good and still abide by the solid principles. And I think we should just keep a minimum length for the password just to have some extra user safety.

**Comment by IbrahimBilal2005** [comment]
Let me know if there are any other issues

**Review by W-Akrabi — APPROVED** [review]
Im very happy with the changes and now I think its ready to merge.

**Comment by IbrahimBilal2005** [comment]
Thank you for your review!

**Pull request merged**
