### PR TITLE
Entity details

### PR DESCRIPTION
**Pull request by IbrahimBilal2005**
Temporary implementation for our entities section to help conceptualize the interface adapters and use cases.

### CODE REVIEW

**Comment by IbrahimBilal2005** [comment]
This is not the final implementation for the entities, but it provides a good base. Feel free to bring up any concerns.

**Review by W-Akrabi — CHANGES_REQUESTED** [review]
The changes align with clean architecture and SOLID principles by introducing the Account interface for flexibility and scalability, adhering to SRP and OCP. However, the EventPoster class mixes account-level and event-related responsibilities, potentially violating SRP; consider separating these concerns. The deletion of Events.java raises questions—was its functionality absorbed into Event or deemed redundant? Please document this to clarify the rationale and ensure no dependencies are broken. Additionally, ensure services depend on abstractions like Account rather than concrete classes, and consider refactoring to improve separation of concerns further.

**Review by W-Akrabi — COMMENTED** [review]
After a nice conversation with Ibrahim, his EventPoster class abides by the SRP

**Comment by IbrahimBilal2005** [comment]
Thank you Waleed for our conversation. Beside SOLID, we raised some good points about how we want to manage events and their relationship to EventPosters. We discussed Map/DB implementations and for now decided to keep it as is. However, this is something we should discuss as a group and decide early on.

**Pull request merged**
