### PR TITLE
made a view for the use case for accepting and denying as an admin

### PR DESCRIPTION
**Pull request by Towaiji**

### CODE REVIEW

**Comment by Towaiji** [comment]
also added the files for the usecase

**Review by IbrahimBilal2005 — COMMENTED** [review]
Good work Ali ! 

Admin is a little tricky since it relies on eventposter, event, database logic to be completed, but I think your structure so far is good. Lets see what the other reviewers think, but I suggest that you continue to make commits to this branch as we finalize admin functionality.

**Review by W-Akrabi — APPROVED** [review]
I believe the structure looks good for now but its too early to say. The screen however looks proper.

**Comment by Towaiji** [comment]
please review the implementations of the usecases

**Comment by W-Akrabi** [comment]
I was just going through your and you are adhering to SOLID and clean architecture pretty well but i noticed that no tests have been added. Just want to remind you of that.

**Comment by TanayLanghe** [comment]
Well done following SOLID, basic set up for use case is there now you just need to incorporate the Data Access to complete the logic required. Great job overall!

**Pull request merged**
