### PR TITLE
Signup user interests implementation + All current tests now passing

### PR DESCRIPTION
**Pull request by IbrahimBilal2005**
- Users can now pick interests when signing up. I added the missing first name, last name, and interest fields for user signup, and removed the tags field for event signup (since we decided events are event specific, and not event poster specific)
- The gender selection process is now a ComboBox instead of a textfield. This will help keep our user's from picking genders that our program doesnt recognize. 
- Also, any interest or gender list is provided in the signupView, so it is really easy to change without adjusting any code in the view classes. 
- I adjusted the signup process to align with the strategy creation implementations. The signup use case is now working as expected. 

- Additionally, all the current tests for both event poster signup and user signup are passing, meaning our implementation and flow is working as expected.

- My next step with signup is to work on specific error handling (ie. invalid names, no inputs provided, etc) These details will be added in my next pull request

### CODE REVIEW

**Comment by IbrahimBilal2005** [comment]
Can you be more specific about where there is high coupling between the UI and business logic?

**Comment by IbrahimBilal2005** [comment]
Do you mind being more specific about where there is high coupling between the UI and business logic? 

I'll be adding more edge-case tests as I implement more specific error functionality, so that is already in the pipline, thanks for pointing it out.

**Comment by W-Akrabi** [comment]
I think im taking coupling a little to seriously but please advise if I'm wrong

**Comment by IbrahimBilal2005** [comment]
I'm just not sure which part of the code you're referring to. If there's a specific part that looks like it has high coupling, let me know so I an address it directly

**Pull request merged**
