### PR TITLE
Logout use case *NEW REQUEST

### PR DESCRIPTION
**Pull request by IbrahimBilal2005**
I cherry-picked the commits from the old logout branch that mixed mongoDB commits and put them in a new branch focused just on logout. 

As before, I've completed the logout use case files

### CODE REVIEW

**Comment by IbrahimBilal2005** [comment]
it is essentially going to set the current user to null. This code will make more sense when the logout button and other related views and logic are completed.

**Comment by W-Akrabi** [comment]
my bad homie i meant to say logout, but this makes sense

**Review by W-Akrabi — APPROVED** [review]
the final implementation looks good. I believe it was the use of the login use case that was the final peace so amazing work.

**Comment by W-Akrabi** [comment]
I will merge it now after speaking with the rest of the group members

**Pull request merged**
