### PR TITLE
Signup Interactors and Tests completed

### PR DESCRIPTION
**Pull request by IbrahimBilal2005**
Completed the signup usecase interactors for both eventposter and user. 
Also completed the interactor Test classes for both interactors with all relevant test methods. 

These test will not pass since we still need to figure out the implementation for interests and tags (combobox, textfield, how many total words to pick, choose from given list or open ended input etc.) 
These are things we can discuss in lab and then I can implement it into my signup logic.

### CODE REVIEW

**Comment by W-Akrabi** [comment]
can you elaborate on the "need to figure out the implementation for interests and tags" How I implemented my search use case was like:
Users enter a keyword into the search bar.
Users can specify tags (e.g., "sports, outdoor") using filters.
These inputs are passed to the SearchController, which prepares a SearchInputData object containing the keyword (category) and tags.
The interactor queries the data access layer using the provided inputs and fetches relevant results.
Results Handling:

Results are passed back to the SearchPresenter, which updates the SearchViewModel with either the results or an error message ("No events found").
The Home_screen dynamically updates the UI to display the results.

because we already have a search bar so I personally think that's good enough no?

**Comment by W-Akrabi** [comment]
Also is the sign up use case affected by the interests and tags?

**Comment by IbrahimBilal2005** [comment]
If we want a good filtering system then the tags for event posters and interests for users should be connected. 

We were still discussing if we want users to input any interest, or if we want to give them a list of choices to select from. 

We were also still discussing if we want to limit how many interests/tags users/event-posters can choose.

That's why for now I didn't implement the interest and tag input sections for signup until we finalize our tags/interests system.

**Comment by W-Akrabi** [comment]
Ok great. Your unit tests for testing the sign up part if the use case is passing though right? like User data validation (e.g., email format, password strength), Error handling for missing or invalid data, Overall user flow up to where the interests selection is skipped.

**Comment by IbrahimBilal2005** [comment]
Like I said, I can't pass my tests until I can create user and event poster objects. I can't do that until my signup input data and related logic takes tags/interests as mentioned in your account strategy classes. I can't do that until we discuss how we want to structure this process in signup. 

The structure and code of the tests is all there, and once we've figured out how to implement interests and tags, and I've incorporated them into the signup process, the tests will pass.

**Review by W-Akrabi — COMMENTED** [review]
Amazing job catching your mistake.

**Review by W-Akrabi — APPROVED** [review]
The recent demonstrate solid progress, particularly with the introduction of an in-memory data access object and improved modular design through interfaces, showcasing a strong grasp of clean architecture principles. However, there is room for improvement in streamlining the event poster signup flow, as some areas could benefit from more concise validation logic to reduce redundancy. Overall, the project is advancing well, and i believe we can merge your final changes.

**Pull request merged**
